ALTER TABLE "PhotographerPortfolioItem"
  ADD COLUMN "coverCropX" DOUBLE PRECISION,
  ADD COLUMN "coverCropY" DOUBLE PRECISION,
  ADD COLUMN "coverCropWidth" DOUBLE PRECISION,
  ADD COLUMN "coverCropHeight" DOUBLE PRECISION;
